### ISSUE TITLE
64 bit support

### ISSUE THREAD

**Issue by wastedabuser** [StickSports/ANE-In-App-Purchase#8]
So i got: Error: META-INF/ANE/iPhone-ARM/libGameCenterIosExtension.a, META-INF/ANE/iPhone-ARM/libInAppPurchaseIosExtension.a are required to have universal iOS libraries.
 Please contact the ANE developer(s) to get the same.

It seems this is expected with the new compiler and Air 16
Does anyone with the proper build setup still using this extension (so he could rebuild the ane)?

**Comment by LucaIaco** [comment]
I recompiled the extension with the support for **armv7** and **arm64**. 
SDK version 8.3, min iOS version 7.0. Here the link to the file:

https://mega.co.nz/#!E1QBVB4B!Y9gfkt3Paq-JlsZoId-d-pcAxO8xN2XFUC3PbJkygb0

**Comment by wastedabuser** [comment]
Thanks @LucaIaco, but i am using different extension now :)
